# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- name: numeSpartan
  value: Vlad

parameters:
  - name: numeDacic
    displayName: 'Nume:'

pool:
  vmImage: ubuntu-latest


stages:
  - stage:
    displayName: My first stage
    jobs:
      - job:
        displayName: My first job
        steps:
          - script: echo Hello, world!
            displayName: 'Run a one-line script'

          - script: |
              echo Add other tasks to build, test, and deploy your project.
              echo See https://aka.ms/yaml
            displayName: 'Run a multi-line script test'
            
  - stage:
    displayName: My second stage
    jobs:
      - job:
        displayName: My first job
        steps:
          - script: echo Hello, world!
            displayName: 'Run a one-line script'
            
          - script: |
              echo Nume spartani!
              echo $(numeSpartan)
              echo ${{ parameters.numeDacic }}
            displayName: 'Run a one-line script'
          
          - script:
              echo ${{ parameters.numeDacic }}>fisier.txt
            displayName: 'Write file'
          
          - publish: fisier.txt
            name: guru
            displayName: Bau bau
      - job:
        displayName: Build C# program
        steps:
          - script: |
              dotnet build CSharp/SimpleApp.csproj -r win10-x64
            workingDirectory: CSharp

          - publish: CSharp/SimpleApp/bin/Debug/net6.0
            name: CSharp
            displayName: CSharp Simple App Build 

      - job:
        displayName: Javascript program
        steps: 
          - script: |
              npm install
              npm test
            workingDirectory: Javascript

          - publish: Javascript/mocha
            name: Javascript
            displayName: Javascript Mocha Unit tests
           