trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage:
    displayName: Build programs
    jobs:
      - job:
        displayName: Build CSharp program
        steps:
          - script: |
              dotnet build HelloWorld/HelloWorld.csproj -r win-x64
            workingDirectory: CSharp
            displayName: Build CSharp Program

          - publish: CSharp/HelloWorld/bin/Debug/net6.0
            name: CSharp
            displayName: Publish CSharp Program
            artifact: CSharp
            
      - job:
        displayName: Run Python program
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
        
          - script: |
              python helloworld.py
            workingDirectory: Python
            displayName: Run Python Program
            
      - job:
        displayName: Run UnitTests Node.js
        steps:
            - script: |
                 npm install
                 npm install mocha
                 npm test
              workingDirectory: NodeJS
              displayName: Run UnitTests Node.js